# where to save your prediect result
save_dir: eval_result/



tasks:
    Anomaly_Information_Tracing_En:
        type: text
        data_path: datasets/en/anomaly_information_tracing_en.jsonl
        compare_func:
            path: benchmark_code/BizFinBench.v2/eval_AEA_2.py
    Conterfactual_En:
        type: text
        data_path: datasets/en/conterfactual_en.jsonl
        compare_func:
            path: benchmark_code/BizFinBench.v2/eval_financial_calculation_2.py
    Event_Logic_Reasoning_En:
        type: text
        data_path: datasets/en/event_logic_reasoning_en.jsonl
        compare_func:
            path: benchmark_code/BizFinBench.v2/eval_financial_logic_event.py
    Financial_Data_Description_En:
        type: text
        data_path: datasets/en/financial_data_description_en.jsonl
        compare_func:
            path: benchmark_code/BizFinBench.v2/eval_financial_description_no_cot.py
    Financial_Multiturn_Perception_En:
        type: text
        data_path: datasets/en/financial_multi-turn_perception_en.jsonl
        compare_func:
            path: benchmark_code/BizFinBench.v2/eval_multi_round_desc.py
    Financial_Quantitative_Computation_En:
        type: text
        data_path: datasets/en/financial_quantitative_computation_en.jsonl
        compare_func:
            path: benchmark_code/BizFinBench.v2/eval_financial_calculation_2.py
    Stock_Price_Predict_En:
        type: text
        data_path: datasets/en/stock_price_predict_en.jsonl
        compare_func:
            path: benchmark_code/BizFinBench.v2/eval_stock_price_predict_short_term.py
    User_Sentiment_Analysis_En:
        type: text
        data_path: datasets/en/user_sentiment_analysis_en.jsonl
        compare_func:
            path: benchmark_code/BizFinBench.v2/eval_emotion.py  
